// <auto-generated />
namespace IssueTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dodataFotografija_AssignedTo_TipAkcije : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dodataFotografija_AssignedTo_TipAkcije));
        
        string IMigrationMetadata.Id
        {
            get { return "201609051859112_dodataFotografija_AssignedTo_TipAkcije"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
